@startuml

title Usecase 
left to right direction
actor :User:

rectangle Software {
    usecase (Authorization)
    usecase (Track Sleep)

    :User: -- (Authorization)
    (Authorization) .> (Track Sleep) : include
}

@enduml
